use crate::fraction;

pub const JUST_INTONATION: [fraction::Fraction; 12] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(17, 16),
    fraction::Fraction(9, 8),
    fraction::Fraction(19, 16),
    fraction::Fraction(5, 4),
    fraction::Fraction(4, 3), // 21/16
    fraction::Fraction(45, 32),
    fraction::Fraction(3, 2),
    fraction::Fraction(51, 32),
    fraction::Fraction(27, 16),
    fraction::Fraction(57, 32),
    fraction::Fraction(15, 8),
];

pub const JUST_INTONATION_24: [fraction::Fraction; 24] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(33, 32),
    fraction::Fraction(17, 16),
    fraction::Fraction(35, 32),
    fraction::Fraction(9, 8),
    fraction::Fraction(37, 32),
    fraction::Fraction(19, 16),
    fraction::Fraction(39, 32),
    fraction::Fraction(5, 4),
    fraction::Fraction(41, 32),
    fraction::Fraction(4, 3), // 85/64
    fraction::Fraction(11, 8),
    fraction::Fraction(45, 32),
    fraction::Fraction(93, 64),
    fraction::Fraction(3, 2),
    fraction::Fraction(99, 64),
    fraction::Fraction(51, 32),
    fraction::Fraction(105, 64),
    fraction::Fraction(27, 16),
    fraction::Fraction(111, 64),
    fraction::Fraction(57, 32),
    fraction::Fraction(117, 64),
    fraction::Fraction(15, 8),
    fraction::Fraction(31, 16),
];

pub const PYTHOGREAN_TUNING: [fraction::Fraction; 12] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(256, 243),
    fraction::Fraction(9, 8),
    fraction::Fraction(32, 27),
    fraction::Fraction(81, 64),
    fraction::Fraction(4, 3),
    fraction::Fraction(729, 512),
    fraction::Fraction(3, 2),
    fraction::Fraction(27, 16),
    fraction::Fraction(16, 9),
    fraction::Fraction(243, 128),
    fraction::Fraction(15, 8),
];

pub const FIVE_LIMIT: [fraction::Fraction; 12] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(16, 15),
    fraction::Fraction(9, 8),
    fraction::Fraction(6, 5),
    fraction::Fraction(5, 4),
    fraction::Fraction(4, 3),
    fraction::Fraction(64, 45),
    fraction::Fraction(3, 2),
    fraction::Fraction(8, 5),
    fraction::Fraction(5, 3),
    fraction::Fraction(16, 9),
    fraction::Fraction(15, 8),
];

pub const ELEVEN_LIMIT: [fraction::Fraction; 29] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(12, 11),
    fraction::Fraction(11, 10),
    fraction::Fraction(10, 9),
    fraction::Fraction(9, 8),
    fraction::Fraction(8, 7),
    fraction::Fraction(7, 6),
    fraction::Fraction(6, 5),
    fraction::Fraction(11, 9),
    fraction::Fraction(5, 4),
    fraction::Fraction(14, 11),
    fraction::Fraction(9, 7),
    fraction::Fraction(4, 3),
    fraction::Fraction(11, 8),
    fraction::Fraction(7, 5),
    fraction::Fraction(10, 7),
    fraction::Fraction(16, 11),
    fraction::Fraction(3, 2),
    fraction::Fraction(14, 9),
    fraction::Fraction(11, 7),
    fraction::Fraction(8, 5),
    fraction::Fraction(18, 11),
    fraction::Fraction(5, 3),
    fraction::Fraction(12, 7),
    fraction::Fraction(7, 4),
    fraction::Fraction(16, 9),
    fraction::Fraction(9, 5),
    fraction::Fraction(20, 11),
    fraction::Fraction(11, 6),
];

pub const FORTYTHREE_TONE: [fraction::Fraction; 43] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(81, 80),
    fraction::Fraction(33, 32),
    fraction::Fraction(21, 20),
    fraction::Fraction(16, 15),
    fraction::Fraction(12, 11),
    fraction::Fraction(11, 10),
    fraction::Fraction(10, 9),
    fraction::Fraction(9, 8),
    fraction::Fraction(8, 7),
    fraction::Fraction(7, 6),
    fraction::Fraction(32, 27),
    fraction::Fraction(6, 5),
    fraction::Fraction(11, 9),
    fraction::Fraction(5, 4),
    fraction::Fraction(14, 11),
    fraction::Fraction(9, 7),
    fraction::Fraction(21, 16),
    fraction::Fraction(4, 3),
    fraction::Fraction(27, 20),
    fraction::Fraction(11, 8),
    fraction::Fraction(7, 5),
    fraction::Fraction(10, 7),
    fraction::Fraction(16, 11),
    fraction::Fraction(40, 27),
    fraction::Fraction(3, 2),
    fraction::Fraction(23, 21),
    fraction::Fraction(14, 9),
    fraction::Fraction(11, 7),
    fraction::Fraction(8, 5),
    fraction::Fraction(18, 11),
    fraction::Fraction(5, 3),
    fraction::Fraction(27, 16),
    fraction::Fraction(12, 7),
    fraction::Fraction(7, 4),
    fraction::Fraction(16, 8),
    fraction::Fraction(9, 5),
    fraction::Fraction(20, 11),
    fraction::Fraction(11, 6),
    fraction::Fraction(15, 8),
    fraction::Fraction(40, 21),
    fraction::Fraction(64, 33),
    fraction::Fraction(160, 81),
];

pub const INDIAN_SCALE: [fraction::Fraction; 8] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(9, 8),
    fraction::Fraction(5, 4),
    fraction::Fraction(4, 3),
    fraction::Fraction(3, 2),
    fraction::Fraction(5, 3),
    fraction::Fraction(27, 16),
    fraction::Fraction(15, 8),
];

pub const INDIAN_SCALE_FULL: [fraction::Fraction; 22] = [
    fraction::Fraction(1, 1),
    fraction::Fraction(256, 243),
    fraction::Fraction(16, 15),
    fraction::Fraction(10, 9),
    fraction::Fraction(9, 8),
    fraction::Fraction(32, 27),
    fraction::Fraction(6, 5),
    fraction::Fraction(5, 4),
    fraction::Fraction(81, 64),
    fraction::Fraction(4, 3),
    fraction::Fraction(27, 20),
    fraction::Fraction(45, 32),
    fraction::Fraction(729, 512),
    fraction::Fraction(3, 2),
    fraction::Fraction(128, 81),
    fraction::Fraction(8, 5),
    fraction::Fraction(5, 3),
    fraction::Fraction(27, 16),
    fraction::Fraction(16, 9),
    fraction::Fraction(9, 5),
    fraction::Fraction(15, 8),
    fraction::Fraction(243, 128),
];
